import type { Metadata } from "next";


import "./globals.css";

import { League_Spartan } from "next/font/google";

const spartan = League_Spartan({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-spartan"
});





export const metadata: Metadata = {
  title: "Lab Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={spartan.variable}>
      <body className="font-spartan">
        {children}
      </body>
    </html>
  );
}
