import type { Metadata } from "next";
import "./globals.css";
import { League_Spartan } from "next/font/google";
import NavBar from "@/components/core/NavBar";
import prisma from "@/lib/prisma";
import { cookies } from "next/headers";
import {validateSessionToken} from "@/auth/session";
import {getSession} from "@/lib/actions";
import SideBar from "@/components/core/SideBar";

const spartan = League_Spartan({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-spartan"
});

export const metadata: Metadata = {
  title: "Lab Manager",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    let user;
    const session = await getSession();

        if (session) {
            const tSession = await prisma.session.findUnique({
                where: { id: session.id },
                include: {
                    user: true
                }
            })
            user = tSession?.user;
        }


  return (
    <html lang="en" className={spartan.variable}>

      <body className="font-spartan h-screen">

        <div className="flex h-screen">

            <aside className="w-73 h-screen">
                < SideBar />
            </aside>

            <main className="flex-1 overflow-auto">
                <NavBar username={user?.username ?? null} />
                {children}
            </main>
        </div>
      </body>
    </html>
  );
}
