import type { Metadata } from "next";
import "./globals.css";
import { League_Spartan } from "next/font/google";
import NavBar from "@/components/core/NavBar";
//import {PopupProvider} from "./popupProvider"
import SideBar from "@/components/core/SideBar";
import {SideViewProvider} from "@/app/sideViewContext";
import {getUser} from "@/lib/actions/userActions";

const spartan = League_Spartan({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
    variable: "--font-spartan"
});

export const metadata: Metadata = {
  title: "Lab Manager",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const user = await getUser();

  return (
    <html lang="en" className={spartan.variable}>
      <body className="font-spartan h-screen">
        <SideViewProvider initialType="">
            <div className="flex h-screen">

                <aside className="w-73 h-screen">
                    < SideBar />
                </aside>

                <main className="flex-1 overflow-auto">
                    <NavBar username={user?.username ?? "Unknown"} />
                    {children}
                </main>
            </div>
        </SideViewProvider>
      </body>
    </html>
  );
}
